# Header
menu:
  Home: /
  Archives: /blog/archives
  GitHub: https://github.com/timonwong
  Twitter: https://twitter.com/timonwong
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-35644871-2
favicon: /favicon.png
twitter: TimonWong
google_plus:
fb_admins:
fb_app_id: