# Header
menu:
  Home: /
  Archives: /blog/archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- about
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-35644871-2
favicon: /favicon.png
twitter: timonwong
google_plus:
fb_admins:
fb_app_id:

# Customizations
github: timonwong
user_title: Timon Wong (timonwong)
gravatar: timon86.wang@gmail.com
email: timon86.wang@gmail.com
weibo: uglifycode
swiftype_key: _Fmagrbt4RavhXm_Hz4j
